name: GdUnit4 Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4           # ソース取得
      - uses: MikeSchulze/gdunit4-action@v1 # ★ 公式 Action
        with:
          godot-version: '4.4.1'            # 使用する Godot Editor
          paths: 'res://tests'              # テストフォルダ
          publish-report: true              # HTML/JUnit をアーティファクト保存
          warnings-as-errors: false