name: GdUnit4 Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdunit4-action@v1
        with:
          godot-version: '4.4.1'
          paths: 'res://tests'
          publish-report: true
